routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\BookController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\CountryController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\PermissionController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\RolePermissionController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\UserPermissionController;
use Illuminate\Foundation\Auth\EmailVerificationRequest;
use Illuminate\Support\Facades\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['verify' => true]);

Route::prefix('cms/')->middleware('guest:admin,user')->group(function () {
    Route::get('{guard}/login', [AuthController::class, 'showLogin'])->name('cms.login');
    Route::post('login', [AuthController::class, 'login']);
});

Route::prefix('cms/admin')->middleware(['auth:admin', 'verified'])->group(function () {
    Route::resource('admins', AdminController::class);
    Route::resource('roles', RoleController::class);
    Route::resource('permissions', PermissionController::class);
    Route::resource('permissions/role', RolePermissionController::class);
    Route::resource('permissions/user-permissions', UserPermissionController::class);
    Route::resource('users', UserController::class);
});

Route::prefix('cms/admin')->middleware(['auth:admin,user', 'verified'])->group(function () {
    Route::get('dashboard/{locale?}', [DashboardController::class, 'showDashboard']);
    Route::resource('books', BookController::class);
    Route::resource('categories', CategoryController::class);
    Route::resource('countries', CountryController::class);

    Route::get('change-password', [AuthController::class, 'showChangePassword'])->name('cms.change-password');
    Route::post('change-password', [AuthController::class, 'changePassword']);

    Route::get('logout', [AuthController::class, 'logout'])->name('cms.logout');
});

Route::get('/email/verify', function () {
    return view('cms.auth.verify-email');
})->middleware('auth')->name('verification.notice');

Route::get('/email/verify/{id}/{hash}', function (EmailVerificationRequest $request) {
    $request->fulfill();
    return redirect('/cms/admin');
})->middleware(['auth:admin', 'signed'])->name('verification.verify');

Route::post('/email/verification-notification', function (Request $request) {
    $request->user()->sendEmailVerificationNotification();

    // return back()->with('message', 'Verification link sent!');
    return response()->json(['message' => 'Verification link sent!']);
})->middleware(['auth:admin', 'throttle:6,1'])->name('verification.send');

// Route::middleware(['age:22','m2','m3'])->group(function () {
//     Route::get('news', function () {
//         return 'WELCOEM IN NEWS PAGE';
//     })->withoutMiddleware('m3');
// });

// Route::middleware('age:22')->get('news', function () {
//     return 'WELCOEM IN NEWS PAGE';
// });

// Route::get('news', function () {
//     return 'WELCOEM IN NEWS PAGE';
// })->middleware('age:22',);


// Route::get('news', function () {
//     return response()->json(['status' => 'success', 'active' => true]);
// })->middleware(CheckAge::class);

app/Models/Book.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Book extends Model
{
    use HasFactory, SoftDeletes;


    public function getVisibilityStatusAttribute()
    {
        return $this->is_visible ? 'Visible' : 'Hidden';
    }


    public function getLanguageNameAttribute()
    {
        return $this->language == 'en' ? 'English' : 'Arabic';
    }

    public function category()
    {
        return $this->belongsTo(Category::class, 'category_id', 'id');
    }
}

app/Http/Controllers/API/BookController.php
<?php

namespace App\Http\Controllers\API;

use App\Http\Controllers\Controller;
use App\Models\Book;
use Illuminate\Http\Request;
use Symfony\Component\HttpFoundation\Response;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // $books = Book::all();
        // $books = Book::paginate(1);
        $books = Book::simplePaginate();
        return response()->json([
            'status' => true, 'message' => 'Success', 'data' => $books
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator($request->all(), [
            'name' => 'required|string|min:3|max:100',
            'year' => 'required|numeric|digits:4',
            'language' => 'required|string|in:en,ar',
            'quantity' => 'required|integer|min:1',
            'visible' => 'required|boolean',
            'image' => 'nullable|image|mimes:jpg,png|size:2048',
            'category_id' => 'required|integer|exists:categories,id'
        ]);

        if (!$validator->fails()) {
            $book = new Book();
            $book->name = $request->get('name');
            $book->year = $request->get('year');
            $book->language = $request->get('language');
            $book->quantity = $request->get('quantity');
            $book->category_id = $request->get('category_id');
            // Category::findOrFail($request->get('category_id'))->books()->save($book);
            $isSaved = $book->save();

            return response()->json([
                'message' => $isSaved ? 'Saved successfully' : 'Failed to create new book!'
            ], $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        } else {
            return response()->json([
                'message' => $validator->getMessageBag()->first()
            ], Response::HTTP_BAD_REQUEST);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
        $validator = Validator($request->all(), [
            'name' => 'required|string|min:3|max:100',
            'year' => 'required|numeric|digits:4',
            'language' => 'required|string|in:en,ar',
            'quantity' => 'required|integer|min:1',
            'visible' => 'required|boolean',
            'image' => 'nullable|image|mimes:jpg,png|size:2048',
            'category_id' => 'required|integer|exists:categories,id'
        ]);

        if (!$validator->fails()) {
            $book->name = $request->get('name');
            $book->year = $request->get('year');
            $book->language = $request->get('language');
            $book->quantity = $request->get('quantity');
            $book->category_id = $request->get('category_id');
            // Category::findOrFail($request->get('category_id'))->books()->save($book);
            $isSaved = $book->save();

            return response()->json([
                'message' => $isSaved ? 'Saved successfully' : 'Failed to create new book!'
            ], $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        } else {
            return response()->json([
                'message' => $validator->getMessageBag()->first()
            ], Response::HTTP_BAD_REQUEST);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        // $deleted = Book::destroy($id);
        $deleted = Book::findOrFail($id)->delete();
        return response()->json([
            'status' => $deleted, 'message' => $deleted ? 'Deleted successfully' : 'Delete failed',
        ], $deleted ? Response::HTTP_OK : Response::HTTP_BAD_REQUEST);
    }
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Models\Book;
use App\Models\Category;
use Dotenv\Validator;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use Symfony\Component\HttpFoundation\Response;

class BookController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        // $books = Book::with('category')->onlyTrashed()->get();
        // $books = Book::with('category')->withoutTrashed()->get();

        $books = Book::with('category')->withTrashed()->get();
        // if(request()->expectsJson()){}
        if (auth('api')->check()) {
            return response()->json(['data' => $books]);
        } else {
            return response()->view('cms.books.index', ['books' => $books]);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $categories = Category::where('is_visible', true)->get();
        return response()->view('cms.books.create', ['categories' => $categories]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $validator = Validator($request->all(), [
            'name' => 'required|string|min:3|max:100',
            'year' => 'required|numeric|digits:4',
            'language' => 'required|string|in:en,ar',
            'quantity' => 'required|integer|min:1',
            // 'visible' => 'required|boolean',
            'visible' => 'required|in:true,false',
            'image' => 'required|image|mimes:jpg,png|max:2048',
            'category_id' => 'required|integer|exists:categories,id'
        ]);

        if (!$validator->fails()) {
            $book = new Book();
            $book->name = $request->get('name');
            $book->year = $request->get('year');
            $book->language = $request->get('language');
            $book->quantity = $request->get('quantity');
            $book->category_id = $request->get('category_id');
            // Category::findOrFail($request->get('category_id'))->books()->save($book);

            if ($request->hasFile('image')) {
                $image = $request->file('image');
                $imageName = time() . '_' . $book->name . '.' . $image->getClientOriginalExtension();
                $request->file('image')->storePubliclyAs('books', $imageName, ['disk' => 'public']);
                $book->image = $imageName;
            }
            $isSaved = $book->save();

            return response()->json([
                'message' => $isSaved ? 'Saved successfully' : 'Failed to create new book!'
            ], $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        } else {
            return response()->json([
                'message' => $validator->getMessageBag()->first()
            ], Response::HTTP_BAD_REQUEST);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function show(Book $book)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function edit(Book $book)
    {
        //
        $categories = Category::where('is_visible', true)->get();
        return response()->view('cms.books.edit', ['book' => $book, 'categories' => $categories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Book $book)
    {
        //
        $validator = Validator($request->all(), [
            'name' => 'required|string|min:3|max:100',
            'year' => 'required|numeric|digits:4',
            'language' => 'required|string|in:en,ar',
            'quantity' => 'required|integer|min:1',
            // 'visible' => 'required|boolean',
            'visible' => 'required|in:true,false',
            'image' => 'nullable|image|mimes:jpg,png|max:2048',
            'category_id' => 'required|integer|exists:categories,id'
        ]);

        if (!$validator->fails()) {
            $book->name = $request->get('name');
            $book->year = $request->get('year');
            $book->language = $request->get('language');
            $book->quantity = $request->get('quantity');
            $book->category_id = $request->get('category_id');
            // Category::findOrFail($request->get('category_id'))->books()->save($book);

            if ($request->hasFile('image')) {
                Storage::disk('public')->delete("books/$book->image");
                $image = $request->file('image');
                $imageName = time() . '_' . $book->name . '.' . $image->getClientOriginalExtension();
                $request->file('image')->storePubliclyAs('books', $imageName, ['disk' => 'public']);
                $book->image = $imageName;
            }
            $isSaved = $book->save();

            return response()->json([
                'message' => $isSaved ? 'Saved successfully' : 'Failed to create new book!'
            ], $isSaved ? Response::HTTP_CREATED : Response::HTTP_BAD_REQUEST);
        } else {
            return response()->json([
                'message' => $validator->getMessageBag()->first()
            ], Response::HTTP_BAD_REQUEST);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Book  $book
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $book = Book::withTrashed()->findOrFail($id);
        $message = '';
        if ($book->trashed()) {
            $status = $book->restore();
            $message = 'Item restored successfully';
        } else {
            $message = 'Item deleted successfully';
            $status = $book->delete();
        }
        if ($status) {
            return response()->json(['title' => $message, 'icon' => 'success']);
        } else {
            return response()->json(['title' => 'Process failed', 'icon' => 'danger']);
        }
    }
}

resources/views/cms/books/create.blade.php
@extends('cms.parent')

@section('title','DEMO')
@section('page-large-name','DEMO')
@section('page-small-name','Demo')

@section('styles')
<!-- Select2 -->
<link rel="stylesheet" href="{{asset('cms/plugins/select2/css/select2.min.css')}}">
<link rel="stylesheet" href="{{asset('cms/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')}}">
@endsection

@section('content')
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title">Create Book</h3>
                    </div>

                    <!-- /.card-header -->
                    <!-- form start -->
                    <form>
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label>Category</label>
                                <select class="form-control categories" id="category_id" style="width: 100%;">
                                    {{-- <option selected="selected">Alabama</option> --}}
                                    @foreach ($categories as $category)
                                    <option value="{{$category->id}}">{{$category->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="name">Name</label>
                                <input type="text" class="form-control" id="name" placeholder="Enter name">
                            </div>
                            <div class="form-group">
                                <label for="description">Year</label>
                                <input type="number" class="form-control" id="year" placeholder="Year">
                            </div>
                            <div class="form-group">
                                <label>Language</label>
                                <select class="form-control languages" id="language" style="width: 100%;">
                                    <option value="en">English</option>
                                    <option value="ar">Arabic</option>
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="description">Quantity</label>
                                <input type="number" class="form-control" id="quantity" placeholder="Quantity">
                            </div>
                            <div class="form-group">
                                <!-- <label for="customFile">Custom File</label> -->
                                <label for="description">Image</label>
                                <div class="custom-file">
                                    <input type="file" class="custom-file-input" id="book_image">
                                    <label class="custom-file-label" for="customFile">Choose file</label>
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="custom-control custom-switch">
                                    <input type="checkbox" class="custom-control-input" name="visible" id="visible"
                                        checked>
                                    <label class="custom-control-label" for="visible">Visible</label>
                                </div>
                            </div>
                        </div>
                        <!-- /.card-body -->

                        <div class="card-footer">
                            <button type="button" onclick="performStore()" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
                <!-- /.card -->
            </div>
            <!--/.col (left) -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
<!-- /.content -->
@endsection

@section('scripts')
<!-- Select2 -->
<script src="{{asset('cms/plugins/select2/js/select2.full.min.js')}}"></script>
<script>
    //Initialize Select2 Elements
    $('.categories').select2({
        theme: 'bootstrap4'
    });
    $('.languages').select2({
        theme: 'bootstrap4'
    });

    function performStore(){
        // let data = {
        //     name: document.getElementById('name').value,
        //     year:document.getElementById('year').value,
        //     quantity:document.getElementById('quantity').value,
        //     category_id: document.getElementById('category_id').value,
        //     language: document.getElementById('language').value,
        //     visible: document.getElementById('visible').checked,
        // }

        let formData = new FormData();
        formData.append('name',document.getElementById('name').value);
        formData.append('year',document.getElementById('year').value);
        formData.append('quantity',document.getElementById('quantity').value);
        formData.append('category_id',document.getElementById('category_id').value);
        formData.append('language',document.getElementById('language').value);
        formData.append('visible',document.getElementById('visible').checked);
        formData.append('image',document.getElementById('book_image').files[0]);
        store('/cms/admin/books',formData);
    }
</script>
@endsection

resources/views/cms/books/index.blade.php
@extends('cms.parent')

@section('title','Books')
@section('page-large-name','Books')
@section('page-small-name','Index')

@section('styles')

@endsection

@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">Bordered Table</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th style="width: 10px">#</th>
                                    <th>Image</th>
                                    <th>Name</th>
                                    <th>Category</th>
                                    <th>Year</th>
                                    <th>Language</th>
                                    <th>Quantity</th>
                                    <th>Visible</th>
                                    <th>Created At</th>
                                    <th>Updated At</th>
                                    <th>Settings</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($books as $book)
                                <tr>
                                    <td>{{$book->id}}</td>
                                    <td>
                                        <img class="img-circle img-bordered-sm" height="60" width="60"
                                            src="{{Storage::url('books/'.$book->image)}}" alt="user image">
                                    </td>
                                    <td>{{$book->name}}</td>
                                    <td>{{$book->category->name}}</td>
                                    <td>
                                        <span class="badge bg-info">{{$book->year}}</span></td>
                                    <td>
                                        <span class="badge bg-success">{{$book->language_name}}</span>
                                    </td>
                                    <td>
                                        <span class="badge bg-primary">({{$book->quantity}}) Book/s</span></td>
                                    </td>
                                    <td>
                                        <span class="badge bg-info">({{$book->visibility_status}})</span></td>
                                    </td>
                                    <td>{{$book->created_at->format('y-m-d H:ma')}}</td>
                                    <td>{{$book->updated_at->format('y-m-d H:ma')}}</td>
                                    <td>
                                        <div class="btn-group">
                                            <a href="{{route('books.edit',$book->id)}}" class="btn btn-info">
                                                <i class="fas fa-edit"></i>
                                            </a>
                                            @if ($book->trashed())
                                            <a onclick="deleteCategory({{$book->id}}, this)" class="btn btn-warning">
                                                <i class="fas fa-trash-restore"></i>
                                            </a>
                                            @else
                                            <a onclick="deleteCategory({{$book->id}}, this)" class="btn btn-danger">
                                                <i class="fas fa-trash"></i>
                                            </a>
                                            @endif

                                            {{-- DELETE | cms/admin/books/{book} --}}
                                            {{-- <form method="POST" action="{{route('books.destroy',$book->id)}}">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-danger">
                                                <i class="fas fa-trash"></i>
                                            </button>
                                            </form> --}}
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                    <div class="card-footer clearfix">

                    </div>
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!-- /.container-fluid -->
</section>
@endsection

@section('scripts')

<script>
    function deleteCategory(id, reference){
        confirmDestroy('/cms/admin/books',id, reference)
    }
</script>
@endsection

{{-- Swal.fire(
'Deleted!',
'Your file has been deleted.',
'success'
) --}}